"""Generate TypeScript contracts directly from Pydantic; check in CI."""

import argparse
import json
from pathlib import Path

from football_intelligence import contracts
from football_intelligence.api import create_app
from football_intelligence.dna import contracts as dna_contracts
from football_intelligence.dna.registry import FAMILIES, FeatureDefinition
from football_intelligence.export import write_json
from football_intelligence.recruitment import contracts as recruitment_contracts
from football_intelligence.recruitment.scoring import specification
from football_intelligence.translation import contracts as translation_contracts

MODELS = [
    "MetricDefinition",
    "Source",
    "Coverage",
    "CompetitionSummary",
    "MatchSummary",
    "PlayerSummary",
    "Explorer",
    "DNAIndex",
    "DNAProfile",
    "DNAMap",
    "DNAEvaluation",
    "DNANeighbor",
    "FeatureDefinition",
    "TranslationIndex",
    "TranslationPlayerDetail",
    "TranslationEvaluation",
    "TranslationModels",
    "RecruitmentIndex",
    "RecruitmentScenario",
    "RecruitmentResult",
    "RecruitmentBootstrap",
    "RecruitmentEvaluation",
    "ClubContext",
]


def ts(schema: dict) -> str:
    if "const" in schema:
        return json.dumps(schema["const"])
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(ts(x) for x in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(x) for x in schema["enum"])
    if schema.get("type") == "object" and "properties" not in schema:
        return f"Record<string, {ts(schema['additionalProperties'])}>"
    if schema.get("type") == "object":
        required = schema.get("required", [])
        return (
            "{\n"
            + "\n".join(
                f"  {k}{'' if k in required else '?'}: {ts(v)};"
                for k, v in schema["properties"].items()
            )
            + "\n}"
        )
    if schema.get("type") == "array":
        return f"Array<{ts(schema['items'])}>"
    return {
        "integer": "number",
        "number": "number",
        "string": "string",
        "boolean": "boolean",
        "null": "null",
    }[schema["type"]]


def generate(check: bool = False):
    schemas = {}
    for name in MODELS:
        model = (
            FeatureDefinition
            if name == "FeatureDefinition"
            else getattr(
                recruitment_contracts
                if name.startswith(("Recruitment", "Club"))
                else translation_contracts
                if name.startswith("Translation")
                else dna_contracts
                if name.startswith("DNA")
                else contracts,
                name,
            )
        )
        schema = model.model_json_schema()
        schemas.update(schema.pop("$defs", {}))
        schemas[name] = schema
    result = (
        "// Generated by scripts/generate_contracts.py. Do not edit.\n"
        + "\n\n".join(f"export type {name} = {ts(schemas[name])};" for name in sorted(schemas))
        + "\n"
    )
    path = Path("apps/web/src/lib/contracts.ts")
    spec_path = Path("apps/web/src/lib/recruitment-spec.json")
    spec_text = json.dumps({**specification(Path.cwd()), "families": FAMILIES}, indent=2) + "\n"
    if check:
        if path.read_text() != result:
            raise SystemExit("TypeScript contracts are stale")
        if not spec_path.exists() or spec_path.read_text() != spec_text:
            raise SystemExit("Shared recruitment scoring specification is stale")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(result)
        spec_path.write_text(spec_text)
        write_json(Path("artifacts/contracts.schema.json"), schemas)
        write_json(Path("artifacts/openapi.json"), create_app().openapi())


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    generate(parser.parse_args().check)
