"""Generate additive v1.2 contracts without modifying earlier scientific schemas."""

import argparse
import json
from pathlib import Path

from generate_contracts import ts

from football_intelligence.expansion import contracts
from football_intelligence.profiles.cache import write_json

MODELS = [
    "ExpandedIndex",
    "ExpandedDetail",
    "NativeRegistry",
    "NativeLeague",
    "MetadataDirectory",
    "MetadataClub",
    "MetadataPeople",
    "MetadataFixtures",
    "PhysicalPerson",
    "PhysicalIndex",
    "ExpansionManifest",
]


def generate(check=False):
    schemas = {}
    for name in MODELS:
        schema = getattr(contracts, name).model_json_schema()
        schemas.update(schema.pop("$defs", {}))
        schemas[name] = schema
    result = (
        "// Generated by scripts/generate_expansion_contracts.py. Do not edit.\n"
        + "\n\n".join(f"export type {name} = {ts(schemas[name])};" for name in sorted(schemas))
        + "\n"
    )
    path = Path("apps/web/src/lib/expansion-contracts.ts")
    schema_path = Path("artifacts/v12/contracts.schema.json")
    if check:
        if path.read_text() != result or json.loads(schema_path.read_text()) != schemas:
            raise SystemExit("v1.2 contracts are stale")
    else:
        path.write_text(result)
        write_json(schema_path, schemas)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    generate(parser.parse_args().check)
