// Generated by scripts/generate_contracts.py. Do not edit.
export type ClubContext = {
  version?: "club-context-v1";
  provider?: "statsbomb";
  club_id: string;
  name: string;
  competition: string;
  season: string;
  observation_start: string;
  observation_end: string;
  matches: number;
  team_minutes: number;
  source_revision: string;
  feature_version?: "features-v1";
  features: Array<ClubFeature>;
  roles: Array<ClubRoleContext>;
};

export type ClubFeature = {
  feature_id: string;
  value: number | null;
  percentile: number | null;
  available_matches: number;
};

export type ClubRoleContext = {
  role: string;
  players: Array<RosterPlayer>;
  reliable_minutes: number;
  roster_depth: number;
  profile_depth: number;
  top_player_minutes_share: number | null;
  minutes_hhi: number | null;
  median: Record<string, number>;
  p25: Record<string, number>;
  p75: Record<string, number>;
  minimum: Record<string, number>;
  maximum: Record<string, number>;
};

export type CompetitionSummary = {
  id: string;
  provider: string;
  name: string;
  season: string;
};

export type Coverage = {
  schema_version: string;
  generated_at: string;
  providers: Array<CoverageRow>;
  validation_status: string;
  warnings: Array<string>;
};

export type CoverageRow = {
  provider: string;
  competitions: number;
  seasons: number;
  matches: number;
  teams: number;
  players: number;
  events: number | null;
  tracking_frames: number | null;
  tracking_objects: number | null;
  date_start: string;
  date_end: string;
  missing_player_events: number | null;
  undetected_objects: number | null;
  available_metrics: Array<string>;
};

export type DNAContribution = {
  feature: string;
  standardized_difference: number;
  squared_contribution: number;
  share: number;
};

export type DNAEvaluation = {
  version: string;
  default_method: string;
  bootstrap_samples: number;
  seed: number;
  rows: Array<DNAEvaluationRow>;
};

export type DNAEvaluationRow = {
  method: string;
  threshold: number;
  eligible: number;
  queries: number;
  recall1: number | null;
  recall5: number | null;
  recall10: number | null;
  mrr: number | null;
  bootstrap_jaccard: number;
  random_recall5: number;
};

export type DNAFeatureValue = {
  id: string;
  value: number | null;
  percentile: number | null;
};

export type DNAIndex = {
  version: string;
  cohort: string;
  competition: string;
  season: string;
  thresholds: Array<number>;
  default_threshold: number;
  matches: number;
  players: Array<DNAPlayer>;
};

export type DNAMap = {
  threshold: number;
  method: "PCA";
  explained_variance: Array<number>;
  points: Array<DNAMapPoint>;
};

export type DNAMapPoint = {
  player_id: string;
  name: string;
  teams: Array<string>;
  role: string;
  minutes: number;
  x: number;
  y: number;
};

export type DNANeighbor = {
  player_id: string;
  name: string;
  teams: Array<string>;
  role: string;
  minutes: number;
  rank: number;
  distance: number;
  stability: number;
  similar: Array<string>;
  different: Array<string>;
  contributions: Array<DNAContribution>;
  family_contributions: Record<string, number>;
};

export type DNAPlayer = {
  player_id: string;
  name: string;
  teams: Array<string>;
  competition: string;
  season: string;
  primary_role: string | null;
  secondary_role: string | null;
  role_shares: Record<string, number>;
  multi_role: boolean;
  minutes: number;
  appearances: number;
  unreliable_appearances: number;
  eligibility: Record<string, Array<string>>;
};

export type DNAProfile = {
  player: DNAPlayer;
  version?: string;
  cohort: string;
  threshold: number;
  eligible: boolean;
  exclusions: Array<string>;
  comparison_size: number;
  features: Array<DNAFeatureValue>;
  scaled_vector: Array<number> | null;
  neighbors: Array<DNANeighbor>;
  neighbor_jaccard: number | null;
  bootstrap_samples: number;
  bins: Array<Array<number>>;
};

export type EventCount = {
  event_type: string;
  count: number;
};

export type Explorer = {
  schema_version: string;
  match: MatchSummary;
  players: Array<PlayerSummary>;
  event_counts: Array<EventCount>;
  spatial_bins: Array<SpatialBin>;
  spatial_sample_size: number;
  tracking_snapshots: Array<TrackingSnapshot>;
};

export type FeatureDefinition = {
  id: string;
  label_en: string;
  label_nl: string;
  family: string;
  unit: string;
  formula: string;
  note_en: string;
  note_nl: string;
  core: boolean;
  intended_use: string;
  source?: string;
  higher_is?: string;
  eligibility?: string;
  null_semantics?: string;
  version?: string;
};

export type MatchSummary = {
  id: string;
  provider: string;
  competition: string;
  season: string;
  date: string;
  home: string;
  away: string;
  score: string;
  coverage: string;
};

export type MetricDefinition = {
  id: string;
  label_en: string;
  label_nl: string;
  unit: string;
  kind: "derived" | "provider_estimate" | "observed";
  providers: Array<string>;
  description_en: string;
  description_nl: string;
  formula?: string | null;
};

export type PlayerSummary = {
  id: string;
  match_id: string;
  provider: string;
  name: string;
  team: string;
  position: string | null;
  minutes: number | null;
  minutes_method: string;
  shots: number | null;
  passes: number | null;
  xg: number | null;
  shots_per90: number | null;
  pass_completion: number | null;
};

export type RecruitmentBootstrap = {
  version?: "recruitment-bootstrap-v1";
  role: string;
  seed: number;
  samples: number;
  scale: number;
  feature_ids: Array<string>;
  player_ids: Array<string>;
  values: Array<Array<Array<number>>>;
};

export type RecruitmentCandidate = {
  player_id: string;
  name: string;
  team_ids: Array<string>;
  teams: Array<string>;
  role: string | null;
  minutes: number;
  appearances: number;
  eligible: boolean;
  exclusions: Array<string>;
  neighbor_stability: number | null;
  percentiles: Record<string, number>;
  multi_club: boolean;
};

export type RecruitmentClubSummary = {
  club_id: string;
  name: string;
  season: string;
  matches: number;
};

export type RecruitmentConstraints = {
  source?: "user_defined";
  minimum_minutes?: number;
  minimum_neighbor_stability?: number;
  exclude_same_club?: boolean;
  candidate_team_id?: string | null;
  provider?: "statsbomb";
  comparison_cohort?: "wsl_2023_24";
};

export type RecruitmentContribution = {
  feature_id: string;
  family: string;
  candidate: number;
  target: number;
  mismatch: number;
  effective_weight: number;
  squared_contribution: number;
  share: number;
  source: "user_defined" | "observed_club_context" | "replacement_player" | "derived_roster_gap";
};

export type RecruitmentEvaluation = {
  version?: "recruitment-fit-evaluation-v1";
  selected_method: string;
  transfer_success_evaluation?: "no_go";
  rows: Array<RecruitmentEvaluationRow>;
  robustness_scenarios: number;
  weight_mean_jaccard: number;
  profile_mean_jaccard: number;
  frontier_median_size: number;
  small_pool_scenarios: number;
};

export type RecruitmentEvaluationRow = {
  stage: string;
  task: string;
  method: string;
  queries: number;
  recall5: number | null;
  recall10: number | null;
  mrr: number | null;
  random_recall5: number | null;
  random_recall10: number | null;
  random_mrr: number | null;
};

export type RecruitmentExclusion = {
  player_id: string;
  reasons: Array<string>;
};

export type RecruitmentFeature = {
  id: string;
  label_en: string;
  label_nl: string;
  family: string;
  unit: string;
  formula: string;
  note_en: string;
  note_nl: string;
  core: boolean;
  intended_use: string;
  source?: string;
  higher_is?: string;
  eligibility?: string;
  null_semantics?: string;
  version?: string;
  recruitment_relevance: Array<"CB" | "FB/WB" | "DM" | "CM" | "AM" | "W" | "ST">;
  default_visibility: Array<"CB" | "FB/WB" | "DM" | "CM" | "AM" | "W" | "ST">;
};

export type RecruitmentIndex = {
  version?: "recruitment-fit-v1";
  requirements_version?: "requirements-v1";
  club_context_version?: "club-context-v1";
  dna_version?: "player-dna-v1";
  feature_version?: "features-v1";
  cohort?: "wsl_2023_24";
  season?: "2023/2024";
  competition: string;
  observation_start: string;
  observation_end: string;
  roles: Array<string>;
  players: Array<RecruitmentCandidate>;
  clubs: Array<RecruitmentClubSummary>;
  features: Array<RecruitmentFeature>;
  method: "weighted_rms" | "family_rms";
};

export type RecruitmentRank = {
  player_id: string;
  rank: number;
  distance: number;
  contributions: Array<RecruitmentContribution>;
  family_contributions: Record<string, number>;
  strong_matches: Array<string>;
  main_mismatches: Array<string>;
  frontier: boolean;
};

export type RecruitmentRequirement = {
  requirement_id: string;
  type?: "style_preference" | "target_profile" | "club_context";
  source?: "user_defined" | "observed_club_context" | "replacement_player" | "derived_roster_gap";
  feature_id: string;
  preference: "exact" | "minimum" | "maximum" | "neutral";
  value: number;
  weight?: 1 | 2 | 3;
  hard_constraint?: boolean;
};

export type RecruitmentResult = {
  version?: "recruitment-fit-v1";
  status: "ok" | "no_requirements" | "no_candidates";
  eligible_count: number;
  active_requirements: number;
  frontier_count: number;
  rankings: Array<RecruitmentRank>;
  exclusions: Array<RecruitmentExclusion>;
};

export type RecruitmentScenario = {
  version?: "requirements-v1";
  fit_method_version?: "recruitment-fit-v1";
  club_id: string;
  season?: "2023/2024";
  target_role: "CB" | "FB/WB" | "DM" | "CM" | "AM" | "W" | "ST";
  mode?: "find" | "replace";
  replacement_player_id?: string | null;
  requirements?: Array<RecruitmentRequirement>;
  hard_constraints?: RecruitmentConstraints;
  family_weights?: Record<string, 1 | 2 | 3>;
  translation_mode?: "observed_only";
  created_from?: "custom" | "replacement" | "adjusted_replacement" | "shared";
};

export type RosterPlayer = {
  player_id: string;
  name: string;
  minutes: number;
  role: string | null;
  profile_eligible: boolean;
  percentiles: Record<string, number>;
  exclusions: Array<string>;
};

export type Source = {
  id: string;
  name: string;
  url: string;
  license: string;
  license_url: string;
  attribution: string;
  limitation_en: string;
  limitation_nl: string;
  revision: string;
};

export type SpatialBin = {
  x: number;
  y: number;
  count: number;
};

export type TrackingPoint = {
  x: number;
  y: number;
  name: string;
  team: string | null;
  object_type: string;
  is_detected: boolean | null;
};

export type TrackingSnapshot = {
  frame: number;
  timestamp_seconds: number;
  period: number;
  points: Array<TrackingPoint>;
};

export type TranslationEnvironment = {
  environment_id: string;
  team_id: string;
  team: string;
  competition: string;
  season: string;
  start_date: string;
  end_date: string;
  role: string | null;
  role_shares: Record<string, number>;
  reliable_minutes: number;
  appearances: number;
  used_as_development_outcome: boolean;
  supported: boolean;
  exclusions: Array<string>;
};

export type TranslationEstimate = {
  metric: string;
  method: string;
  observed_source: number;
  expected_target: number;
  p10: number;
  p90: number;
  p025: number;
  p975: number;
  interval_kind: "posterior_predictive" | "empirical_predictive";
  expected_rate_p10?: number | null;
  expected_rate_p90?: number | null;
};

export type TranslationEvaluation = {
  model_version: string;
  train: number;
  validation: number;
  test: number;
  test_period: Array<string>;
  test_team_changes: number;
  max_rhat: number;
  divergences: number;
  rows: Array<TranslationEvaluationRow>;
};

export type TranslationEvaluationRow = {
  metric: string;
  method: string;
  n: number;
  mae: number;
  rmse: number;
  coverage50: number;
  coverage80: number;
  coverage95: number;
  width80: number;
  selected: boolean;
};

export type TranslationEvidence = {
  direct_episodes: number;
  direct_players: number;
  target_team_role_episodes: number;
  role_episodes: number;
  development_episodes: number;
  development_seasons: Array<string>;
  relies_on_pooling: boolean;
  unseen_target_team: boolean;
  source_context_matches: number;
  target_context_matches: number;
  context_latest_date: string | null;
};

export type TranslationIndex = {
  version: string;
  translated_profile_version: string;
  feature_version: string;
  observed_dna_version: string;
  scope: string;
  source_season: string;
  target_season: string;
  minimum_minutes: number;
  prediction_minutes: number;
  development_episodes: number;
  test_episodes: number;
  test_team_changes: number;
  players: Array<TranslationPlayer>;
  targets: Array<TranslationTarget>;
  roles: Array<string>;
  metrics: Array<TranslationMetric>;
};

export type TranslationMetric = {
  id: string;
  label_en: string;
  label_nl: string;
  unit?: string;
  selected_method: string;
};

export type TranslationModels = {
  version: string;
  scope: string;
  provider: string;
  source_revision: string;
  feature_version: string;
  observed_dna_version: string;
  supported_competitions: Array<string>;
  development_period: Array<string>;
  heldout_period: Array<string>;
  likelihood: string;
  primary_priors_version: string;
  selected_methods: Record<string, string>;
  model_code_commit: string;
};

export type TranslationPlayer = {
  player_id: string;
  name: string;
  teams: Array<string>;
  supported_sources: number;
};

export type TranslationPlayerDetail = {
  player: TranslationPlayer;
  model_version: string;
  environments: Array<TranslationEnvironment>;
  predictions: Array<TranslationPrediction>;
};

export type TranslationPrediction = {
  model_version: string;
  source_environment_id: string;
  target_environment_id: string;
  target_role: string;
  status: "supported" | "insufficient_evidence" | "out_of_scope";
  exclusions: Array<string>;
  prediction_minutes: number;
  estimates: Array<TranslationEstimate>;
  research_estimates: Array<TranslationEstimate>;
  evidence: TranslationEvidence;
};

export type TranslationTarget = {
  environment_id: string;
  team_id: string;
  team: string;
  competition: string;
  season: string;
};
