// Generated by scripts/generate_contracts.py. Do not edit.
export type CompetitionSummary = {
  id: string;
  provider: string;
  name: string;
  season: string;
};

export type Coverage = {
  schema_version: string;
  generated_at: string;
  providers: Array<CoverageRow>;
  validation_status: string;
  warnings: Array<string>;
};

export type CoverageRow = {
  provider: string;
  competitions: number;
  seasons: number;
  matches: number;
  teams: number;
  players: number;
  events: number | null;
  tracking_frames: number | null;
  tracking_objects: number | null;
  date_start: string;
  date_end: string;
  missing_player_events: number | null;
  undetected_objects: number | null;
  available_metrics: Array<string>;
};

export type EventCount = {
  event_type: string;
  count: number;
};

export type Explorer = {
  schema_version: string;
  match: MatchSummary;
  players: Array<PlayerSummary>;
  event_counts: Array<EventCount>;
  spatial_bins: Array<SpatialBin>;
  spatial_sample_size: number;
  tracking_snapshots: Array<TrackingSnapshot>;
};

export type MatchSummary = {
  id: string;
  provider: string;
  competition: string;
  season: string;
  date: string;
  home: string;
  away: string;
  score: string;
  coverage: string;
};

export type MetricDefinition = {
  id: string;
  label_en: string;
  label_nl: string;
  unit: string;
  kind: "derived" | "provider_estimate" | "observed";
  providers: Array<string>;
  description_en: string;
  description_nl: string;
  formula?: string | null;
};

export type PlayerSummary = {
  id: string;
  match_id: string;
  provider: string;
  name: string;
  team: string;
  position: string | null;
  minutes: number | null;
  minutes_method: string;
  shots: number | null;
  passes: number | null;
  xg: number | null;
  shots_per90: number | null;
  pass_completion: number | null;
};

export type Source = {
  id: string;
  name: string;
  url: string;
  license: string;
  license_url: string;
  attribution: string;
  limitation_en: string;
  limitation_nl: string;
  revision: string;
};

export type SpatialBin = {
  x: number;
  y: number;
  count: number;
};

export type TrackingPoint = {
  x: number;
  y: number;
  name: string;
  team: string | null;
  object_type: string;
  is_detected: boolean | null;
};

export type TrackingSnapshot = {
  frame: number;
  timestamp_seconds: number;
  period: number;
  points: Array<TrackingPoint>;
};
