// Generated by scripts/generate_expansion_contracts.py. Do not edit.
export type CapabilitySet = {
  searchable?: boolean;
  provider_profile?: boolean;
  similarity?: boolean;
  recruitment?: boolean;
  common_profile?: boolean;
  translation?: boolean;
  physical?: boolean;
  metadata_only?: boolean;
};

export type CommonMetrics = {
  non_penalty_shots_per90: number;
  passes_all_per90: number;
  long_passes_all_per90: number;
};

export type ExpandedCounts = {
  providers: number;
  competitions: number;
  provider_competitions: number;
  competition_seasons: number;
  seasons: number;
  matches: number;
  events: number;
  profiles: number;
  provider_identities: number;
  native_profiles: number;
  common_profiles: number;
  similarity_profiles: number;
  translation_profiles: number;
  validated_dna_profiles: number;
  club_seasons: number;
  countries: number;
  recruitment_profiles: number;
  recruitment_clubs: number;
  metadata_clubs: number;
  metadata_player_records: number;
  metadata_competition_seasons: number;
  specialist_profiles: number;
  verified_persons?: 0;
};

export type ExpandedDetail = {
  version: "statsbomb-expanded-profile-v1";
  identity: ProfileIndexEntry;
  provider_player_id: number;
  provider_role: string;
  appearances: number;
  first_date: string;
  last_date: string;
  minute_methods: Array<string>;
  native: StatsBombMetrics;
  common: CommonMetrics | null;
  common_unavailable_reasons: Array<string>;
  similarity_version: "not_evaluated";
  similarity_scope: "not_evaluated";
  similarity_scaling: "not_evaluated";
  neighbours: Array<ProfileNeighbour>;
  dna_player_id?: null;
  provenance: ExpandedProvenance;
};

export type ExpandedEntry = {
  id: string;
  name: string;
  provider: "statsbomb" | "wyscout";
  scope: string;
  teams: Array<string>;
  role: string | null;
  role_family: "GK" | "DEF" | "MID" | "FWD";
  minutes: number;
  capabilities: ProfileCapabilities;
  capabilities_v12: CapabilitySet;
  detail_path: string;
};

export type ExpandedIndex = {
  version: "player-database-v12";
  common_version: "common-profile-v1";
  common_threshold: number;
  search_threshold: 450;
  counts: ExpandedCounts;
  scopes: Array<ExpandedScope>;
  teams: Record<string, string>;
  profiles: Array<ExpandedEntry>;
};

export type ExpandedProvenance = {
  source_revision: string;
  source_files: Array<string>;
  source_manifest_sha256: string;
  feature_manifest_sha256: string;
  build_manifest: "/data/v12/build-manifest.json";
  code_commit: string;
  pipeline_sha256: string;
};

export type ExpandedScope = {
  id: string;
  provider: "statsbomb" | "wyscout";
  competition: string;
  competition_key: string;
  season: string;
  gender: "male" | "female";
  matches: number;
  profiles: number;
  common_profiles: number;
  similarity_profiles: number;
  coverage: string;
  first_date: string;
  last_date: string;
  country: string;
  scope_label: string;
  recruitment: boolean;
  clubs: Array<string>;
};

export type ExpansionManifest = {
  version: "v12-build-v1";
  code_commit: string;
  pipeline_sha256: string;
  source_manifest_sha256: string;
  evaluation_sha256: string;
  counts: ExpandedCounts;
  public_files: number;
  public_bytes: number;
  index_gzip_bytes: number;
  source_bytes: number;
  source_files: number;
  partial: false;
};

export type MetadataClub = {
  id: string;
  name: string;
  country: string;
  aliases: Array<string>;
  stadium: string | null;
  source: string;
  source_line: number | null;
  metadata_updated: string;
  seasons: Array<string>;
  resolution?: string | null;
  performance_scopes: Array<string>;
  capabilities: Record<string, boolean>;
};

export type MetadataClubSummary = {
  id: string;
  name: string;
  country: string;
  aliases: Array<string>;
  seasons: Array<string>;
  performance_scopes: Array<string>;
};

export type MetadataCompetition = {
  id: string;
  name: string;
  country: string;
  season: string;
  competition_code: string;
  clubs: Array<string>;
  fixtures: number;
  results: number;
  source: string;
  provider: string;
  metadata_updated: string;
  capabilities: Record<string, boolean>;
};

export type MetadataDirectory = {
  version: "club-metadata-v1";
  clubs: Array<MetadataClubSummary>;
  competitions: Array<MetadataCompetition>;
  player_countries: Record<string, number>;
  player_paths: Record<string, string>;
  specialist_path: string;
  license: string;
};

export type MetadataFixtures = {
  version: "fixture-metadata-v1";
  scope: string;
  source: string;
  columns: Array<string>;
  rows: Array<Array<string | Array<number> | null>>;
};

export type MetadataPeople = {
  version: "player-metadata-v1";
  country: string;
  metadata_updated: string;
  players: Array<MetadataPerson>;
};

export type MetadataPerson = {
  id: string;
  name: string;
  country: string;
  dob: string | null;
  height_m: number | null;
  position: string;
  source: string;
  source_line: number;
  capabilities: CapabilitySet;
  conflicting_source_rows?: boolean;
};

export type NativeClub = {
  id: string;
  name: string;
  roles: Array<RoleContext>;
  roster_median: Record<string, number>;
  capabilities: Record<string, boolean>;
};

export type NativeFeature = {
  id: string;
  en: string;
  nl: string;
  family: string;
  formula: string;
  event_mapping: string;
  tags_required: Array<number>;
  unit: string;
  null_semantics: string;
  role_suitability: Array<string>;
  research_note: string;
};

export type NativeLeague = {
  version: "recruitment-fit-wyscout-v1";
  context_version: "wyscout-club-context-v1";
  feature_registry_version: "wyscout-recruitment-features-v1";
  scope: string;
  competition: string;
  competition_id: string;
  country: string;
  season: string;
  season_id: string;
  minutes_threshold: number;
  roles: Array<string>;
  clubs: Array<NativeClub>;
  players: Array<NativePlayer>;
  scales: Record<string, Record<string, number>>;
  weights: Record<string, Record<string, number>>;
};

export type NativeLeagueSummary = {
  scope: string;
  competition: string;
  country: string;
  season: string;
  minutes_threshold: number;
  clubs: number;
  profiles: number;
  path: string;
};

export type NativePlayer = {
  id: string;
  name: string;
  scope: string;
  role: "GK" | "DEF" | "MID" | "FWD";
  minutes: number;
  teams: Array<string>;
  features: Record<string, number>;
  percentiles: Record<string, number>;
};

export type NativeRegistry = {
  version: "recruitment-fit-wyscout-v1";
  features: Array<NativeFeature>;
  leagues: Array<NativeLeagueSummary>;
  source: string;
  license: string;
  evaluation_path: string;
};

export type PhysicalIndex = {
  version: "physical-research-v1";
  profiles: Array<PhysicalSummary>;
  source: string;
  license: string;
};

export type PhysicalPerson = {
  id: string;
  provider: "skillcorner";
  provider_player_id: string;
  name: string;
  season: string;
  competition: string;
  country: string;
  teams: Record<string, string>;
  records: Array<PhysicalRecord>;
  capabilities: CapabilitySet;
  scope_note: string;
  source: string;
};

export type PhysicalRecord = {
  kind: "physical" | "obr" | "passing";
  source_file: string;
  values: Record<string, string>;
};

export type PhysicalSummary = {
  id: string;
  name: string;
  season: string;
  competition: string;
  teams: Array<string>;
};

export type ProfileCapabilities = {
  common: boolean;
  similarity: boolean;
  translation: boolean;
  validated_dna: boolean;
};

export type ProfileIndexEntry = {
  id: string;
  name: string;
  provider: "statsbomb" | "wyscout";
  scope: string;
  teams: Array<string>;
  role: string | null;
  role_family: "GK" | "DEF" | "MID" | "FWD";
  minutes: number;
  capabilities: ProfileCapabilities;
};

export type ProfileNeighbour = {
  id: string;
  distance: number;
};

export type RoleContext = {
  role: "GK" | "DEF" | "MID" | "FWD";
  players: Array<string>;
  minutes: number;
  median: Record<string, number>;
  q25: Record<string, number>;
  q75: Record<string, number>;
  percentiles: Record<string, number>;
};

export type StatsBombMetrics = {
  open_play_passes_per90: number | null;
  open_play_completion: number | null;
  crosses_per90: number | null;
  pressures_per90: number | null;
  carries_per90: number | null;
  dribbles_per90: number | null;
  tackles_per90: number | null;
  interceptions_per90: number | null;
  recoveries_per90: number | null;
  non_penalty_xg_per90: number | null;
};
