export const playersCopy = {
  en: {
    title: "Player database",
    intro:
      "Explore observed player-season profiles across open football datasets. Provider, season and evidence stay visible.",
    profiles: "player-season profiles",
    identities: "unique provider identities",
    providers: "providers",
    competitions: "competitions",
    seasons: "competition-seasons",
    matches: "matches",
    commonCount: "common profiles",
    search: "Search players",
    searchHint: "Search player, club or competition",
    provider: "Provider",
    competition: "Competition",
    season: "Season",
    team: "Team",
    role: "Role",
    evidence: "Minimum reliable minutes",
    kind: "Profile type",
    all: "All",
    native: "Observed provider-native profile",
    common: "Common cross-provider profile",
    similarity: "Similarity eligible",
    limited: "450–899 minutes",
    clear: "Clear filters",
    filterCount: "Option counts describe the full database.",
    results: "matching profiles",
    empty: "No profiles match these filters.",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    open: "Open profile",
    compare: "Compare",
    comparison: "Comparison",
    removeComparison: "Remove comparison",
    close: "Close profile",
    selectFirst:
      "Open a profile to inspect its evidence or choose a second profile for comparison.",
    loading: "Loading verified profiles…",
    error:
      "The data could not be loaded or verified. Try again, or reload this release.",
    retry: "Try again",
    minutes: "Reliable minutes",
    appearances: "Appearances",
    unavailable: "Not available",
    source: "Source and provenance",
    metric: "Metric",
    value: "Observed value",
    nativeNote:
      "Provider-native definitions. These extra dimensions can only be compared within the same provider.",
    commonNote:
      "Uses only metrics calculated with harmonised definitions across supported providers.",
    disclaimer:
      "Common profiles use a conservative subset of independently harmonised features. Provider-native profiles may contain additional information and should not be interpreted as numerically identical measurement systems.",
    unsupported:
      "These profiles do not share an available common feature set. No cross-provider comparison is calculated.",
    evidenceNote:
      "Rates use nominal regulation minutes (45 + 45); recorded stoppage-time actions remain in the numerator. Unresolved participation conflicts exclude the whole player-season profile.",
    rolesNote:
      "Wyscout provides broad roles only: DEF, MID and FWD. Detailed positions are not inferred. Goalkeepers have native profiles only.",
    capabilities: "Profile availability",
    dna: "Validated WSL Player DNA",
    translation: "Translation eligible",
    yes: "Available",
    no: "Not eligible",
    shared: "Whole-season aggregate across the listed teams.",
    nativeVersion: "Native feature version",
    commonVersion: "Common feature version",
    build: "Build manifest",
    sourceManifest: "Pinned source files and checksums",
    methods: "Methodology",
    research: "Full evaluation and limitations",
    broadRole: "Provider role / audited role family",
    unavailableCommon:
      "Common profile unavailable: goalkeepers are excluded; all three features and sufficient reliable minutes are required.",
    neighbours: "Within-cohort descriptive neighbours",
    neighboursNote:
      "Three common features, shared development scaling and Euclidean distance. Same provider, competition-season and broad role only. This is not a talent, recruitment or transfer ranking.",
    noNeighbours:
      "This cohort does not have sufficient split-half evidence for similarity.",
    distance: "Profile distance",
    rankingNote:
      "Cross-provider nearest-neighbour rankings are not published. Three shared measures and detectable provider effects do not establish player-style equivalence.",
    coverageTitle: "Expanded observed-profile coverage",
    coverageNote:
      "Counts are player-season profiles, not unique people. Provider identities remain separate. The same competition can appear under both providers; no names are merged.",
    partial: "Partial: 131 of 132 scheduled matches",
    complete: "Selected full domestic season",
    women: "Women",
    men: "Men",
    methodologyTitle: "Provider expansion",
    methodology:
      "StatsBomb Open Data and the academic Pappalardo/Wyscout release retain separate identities and native feature registries. Searchable does not imply validated Player DNA, translation eligibility or recruitment suitability. Existing WSL research stays frozen.",
    harmonisationTitle: "Common profile harmonisation",
    harmonisation:
      "Same label does not guarantee the same measurement. Common v1 retains only non-penalty shots, all pass attempts including restarts, and long pass attempts (≥30 m), per 90. Coordinates use a 105 × 68 m pitch, upper-left origin and attacking direction towards positive x in every period. Four completed-pass candidates were excluded after unknown-outcome coverage checks; no outcomes are imputed.",
    evaluationTitle: "Measured limits",
    evaluation:
      "A fixed provider classifier is evaluated on held-out provider identities in men's shared leagues with matched broad roles. Provider, league, season and gender effects cannot be separated causally. Temporal retrieval and bootstrap results describe stability, not predictive football performance.",
    auc: "Held-out provider ROC AUC",
    balanced: "Balanced accuracy",
    threshold: "Common evidence threshold",
    publication:
      "Derived aggregates only. Raw event files are downloaded separately. StatsBomb research remains non-commercial under its Open Data terms. The Pappalardo/Wyscout academic dataset is CC BY 4.0; no endorsement is implied.",
    male: "Men",
    female: "Women",
    roles: {
      GK: "Goalkeeper",
      DEF: "Defender (broad)",
      MID: "Midfielder (broad)",
      FWD: "Forward (broad)",
      CB: "Centre-back",
      "FB/WB": "Full-back / wing-back",
      DM: "Defensive midfielder",
      CM: "Central midfielder",
      AM: "Attacking midfielder",
      W: "Winger",
      ST: "Striker",
    },
  },
  nl: {
    title: "Spelersdatabase",
    intro:
      "Verken geobserveerde speler-seizoensprofielen uit open voetbaldatasets. Provider, seizoen en onderbouwing blijven zichtbaar.",
    profiles: "speler-seizoensprofielen",
    identities: "unieke provideridentiteiten",
    providers: "providers",
    competitions: "competities",
    seasons: "competitie-seizoenen",
    matches: "wedstrijden",
    commonCount: "gedeelde profielen",
    search: "Spelers zoeken",
    searchHint: "Zoek op speler, club of competitie",
    provider: "Provider",
    competition: "Competitie",
    season: "Seizoen",
    team: "Club",
    role: "Rol",
    evidence: "Minimaal betrouwbare minuten",
    kind: "Profieltype",
    all: "Alle",
    native: "Geobserveerd providerspecifiek profiel",
    common: "Gedeeld profiel over providers heen",
    similarity: "Geschikt voor gelijkenisvergelijking",
    limited: "450–899 minuten",
    clear: "Filters wissen",
    filterCount: "Aantallen bij opties gelden voor de volledige database.",
    results: "overeenkomende profielen",
    empty: "Geen profielen passen bij deze filters.",
    previous: "Vorige",
    next: "Volgende",
    page: "Pagina",
    of: "van",
    open: "Profiel openen",
    compare: "Vergelijken",
    comparison: "Vergelijking",
    removeComparison: "Vergelijking verwijderen",
    close: "Profiel sluiten",
    selectFirst:
      "Open een profiel om de onderbouwing te bekijken, of kies een tweede profiel om te vergelijken.",
    loading: "Gecontroleerde profielen laden…",
    error:
      "De gegevens konden niet worden geladen of gecontroleerd. Probeer opnieuw of herlaad deze versie.",
    retry: "Opnieuw proberen",
    minutes: "Betrouwbare minuten",
    appearances: "Optredens",
    unavailable: "Niet beschikbaar",
    source: "Bron en herkomst",
    metric: "Kenmerk",
    value: "Geobserveerde waarde",
    nativeNote:
      "Providerspecifieke definities. Deze extra dimensies zijn alleen binnen dezelfde provider vergelijkbaar.",
    commonNote:
      "Gebruikt uitsluitend kenmerken met geharmoniseerde definities bij de ondersteunde providers.",
    disclaimer:
      "Gedeelde profielen gebruiken een conservatieve selectie van afzonderlijk geharmoniseerde kenmerken. Providerspecifieke profielen kunnen extra informatie bevatten en vormen geen numeriek identieke meetsystemen.",
    unsupported:
      "Deze profielen delen geen beschikbare gemeenschappelijke kenmerkenset. Er wordt geen vergelijking tussen providers berekend.",
    evidenceNote:
      "Waarden per 90 gebruiken nominale reguliere minuten (45 + 45); geregistreerde acties in blessuretijd tellen mee in de teller. Onopgeloste deelnameconflicten sluiten het volledige speler-seizoensprofiel uit.",
    rolesNote:
      "Wyscout levert alleen brede rollen: DEF, MID en FWD. Gedetailleerde posities worden niet afgeleid. Keepers hebben alleen providerspecifieke profielen.",
    capabilities: "Profielbeschikbaarheid",
    dna: "Gevalideerd WSL-spelers-DNA",
    translation: "Geschikt voor vertaling",
    yes: "Beschikbaar",
    no: "Niet geschikt",
    shared: "Seizoensaggregaat over de genoemde clubs.",
    nativeVersion: "Versie providerspecifieke kenmerken",
    commonVersion: "Versie gemeenschappelijke kenmerken",
    build: "Bouwmanifest",
    sourceManifest: "Vastgelegde bronbestanden en hashes",
    methods: "Methodologie",
    research: "Volledige evaluatie en beperkingen",
    broadRole: "Providerrol / gecontroleerde brede rol",
    unavailableCommon:
      "Gedeeld profiel niet beschikbaar: keepers zijn uitgesloten; alle drie kenmerken en voldoende betrouwbare minuten zijn vereist.",
    neighbours: "Beschrijvende buren binnen het cohort",
    neighboursNote:
      "Drie gemeenschappelijke kenmerken, gedeelde schaling uit ontwikkeldata en euclidische afstand. Alleen dezelfde provider, competitie, seizoen en brede rol. Dit is geen ranglijst voor talent, recruitment of transfers.",
    noNeighbours:
      "Dit cohort heeft onvoldoende onderbouwing uit seizoenshelften voor gelijkenisvergelijking.",
    distance: "Profielafstand",
    rankingNote:
      "Ranglijsten met naaste buren over providers heen worden niet gepubliceerd. Drie gedeelde maten en aantoonbare providerverschillen bewijzen geen gelijkwaardig spelersprofiel.",
    coverageTitle: "Dekking van de uitgebreide profielendatabase",
    coverageNote:
      "Aantallen zijn speler-seizoensprofielen, geen unieke personen. Provideridentiteiten blijven gescheiden. Dezelfde competitie kan bij beide providers voorkomen; namen worden niet samengevoegd.",
    partial: "Gedeeltelijk: 131 van 132 geplande wedstrijden",
    complete: "Geselecteerd volledig competitieseizoen",
    women: "Vrouwen",
    men: "Mannen",
    methodologyTitle: "Uitbreiding met providers",
    methodology:
      "StatsBomb Open Data en de academische Pappalardo/Wyscout-release behouden afzonderlijke identiteiten en eigen kenmerkenregisters. Zoekbaar betekent niet gevalideerd spelers-DNA, geschiktheid voor vertaling of recruitment. Het bestaande WSL-onderzoek blijft bevroren.",
    harmonisationTitle: "Harmonisatie van gedeelde profielen",
    harmonisation:
      "Hetzelfde label garandeert niet dezelfde meting. Common v1 bevat alleen schoten zonder strafschoppen, alle passpogingen inclusief spelhervattingen, en lange passpogingen (≥30 m), per 90. Coördinaten gebruiken een veld van 105 × 68 m, oorsprong linksboven en een aanvalsrichting naar positieve x in elke helft. Vier kandidaten met geslaagde passes zijn na de controle op onbekende uitkomsten uitgesloten; uitkomsten worden niet ingevuld.",
    evaluationTitle: "Gemeten beperkingen",
    evaluation:
      "Een vaste providerclassifier wordt getoetst op apart gehouden provideridentiteiten uit gedeelde mannencompetities, met vergelijkbare brede rollen. Effecten van provider, competitie, seizoen en gender zijn niet causaal te scheiden. Temporele herkenning en bootstrapresultaten beschrijven stabiliteit, geen voorspelde voetbalprestaties.",
    auc: "ROC AUC van providerherkenning op toetsdata",
    balanced: "Gebalanceerde nauwkeurigheid",
    threshold: "Ondergrens voor gedeelde profielen",
    publication:
      "Alleen afgeleide aggregaten. Ruwe eventbestanden worden apart gedownload. StatsBomb-onderzoek blijft niet-commercieel onder de Open Data-voorwaarden. De academische Pappalardo/Wyscout-dataset heeft CC BY 4.0; dit impliceert geen goedkeuring van het project.",
    male: "Mannen",
    female: "Vrouwen",
    roles: {
      GK: "Keeper",
      DEF: "Verdediger (breed)",
      MID: "Middenvelder (breed)",
      FWD: "Aanvaller (breed)",
      CB: "Centrale verdediger",
      "FB/WB": "Back / wingback",
      DM: "Verdedigende middenvelder",
      CM: "Centrale middenvelder",
      AM: "Aanvallende middenvelder",
      W: "Vleugelaanvaller",
      ST: "Spits",
    },
  },
};
