// Generated by scripts/generate_profile_contracts.py. Do not edit.
export type CommonMetrics = {
  non_penalty_shots_per90: number;
  passes_all_per90: number;
  long_passes_all_per90: number;
};

export type ProfileBiasSummary = {
  auc: number;
  balanced_accuracy: number;
  heldout_profiles: number;
};

export type ProfileBuildManifest = {
  version: "player-database-v1";
  code_commit: string;
  pipeline_sha256: string;
  source_manifest_sha256: string;
  feature_manifest_sha256: string;
  evaluation_sha256: string;
  public_files: number;
  public_bytes: number;
  index_bytes: number;
  index_gzip_bytes: number;
  largest_profile_bytes: number;
  counts: ProfileCounts;
  partial: false;
};

export type ProfileCapabilities = {
  common: boolean;
  similarity: boolean;
  translation: boolean;
  validated_dna: boolean;
};

export type ProfileCounts = {
  providers: number;
  competitions: number;
  provider_competitions: number;
  competition_seasons: number;
  seasons: number;
  matches: number;
  events: number;
  profiles: number;
  provider_identities: number;
  native_profiles: number;
  common_profiles: number;
  similarity_profiles: number;
  translation_profiles: number;
  validated_dna_profiles: number;
};

export type ProfileCoverage = {
  version: "player-database-v1";
  counts: ProfileCounts;
  scopes: Array<ProfileScope>;
  common_threshold: number;
  common_features: Array<string>;
  provider_bias: ProfileBiasSummary;
  cross_provider_ranking_enabled: boolean;
  temporal_mrr: Record<string, number>;
  excluded_profiles: Record<string, number>;
  threshold_counts: Record<string, number>;
};

export type ProfileDetail = {
  version: "statsbomb-profile-v2" | "wyscout-profile-v1";
  identity: ProfileIndexEntry;
  provider_player_id: number;
  provider_role: string;
  appearances: number;
  first_date: string;
  last_date: string;
  minute_methods: Array<string>;
  native: StatsBombMetrics | WyscoutMetrics;
  common: CommonMetrics | null;
  common_unavailable_reasons: Array<string>;
  similarity_version: "common-similarity-v1";
  similarity_scope: "same_provider_competition_season_role";
  similarity_scaling: "shared_first_half_development_zscore";
  neighbours: Array<ProfileNeighbour>;
  dna_player_id: string | null;
  provenance: ProfileProvenance;
};

export type ProfileIndex = {
  version: "player-database-v1";
  common_version: "common-profile-v1";
  common_threshold: number;
  search_threshold: 450;
  counts: ProfileCounts;
  scopes: Array<ProfileScope>;
  teams: Record<string, string>;
  profiles: Array<ProfileIndexEntry>;
};

export type ProfileIndexEntry = {
  id: string;
  name: string;
  provider: "statsbomb" | "wyscout";
  scope: string;
  teams: Array<string>;
  role: string | null;
  role_family: "GK" | "DEF" | "MID" | "FWD";
  minutes: number;
  capabilities: ProfileCapabilities;
};

export type ProfileMetricDefinition = {
  id: string;
  en: string;
  nl: string;
  unit: "per90" | "fraction";
  definition_en: string;
  definition_nl: string;
  statsbomb_mapping: string;
  wyscout_mapping: string;
};

export type ProfileNeighbour = {
  id: string;
  distance: number;
};

export type ProfileProvenance = {
  source_revision: string;
  source_files: Array<string>;
  source_manifest_sha256: string;
  feature_manifest_sha256: string;
  build_manifest: "/data/v11/build-manifest.json";
  code_commit: string;
  pipeline_sha256: string;
};

export type ProfileRegistry = {
  version: "common-profile-v1";
  features: Array<ProfileMetricDefinition>;
  statsbomb: Array<ProfileMetricDefinition>;
  wyscout: Array<ProfileMetricDefinition>;
  coordinate_convention: string;
  denominator: string;
  excluded_concepts: Array<string>;
  scaler_policy: string;
  evidence_threshold: number;
  validation_date: string;
  source_versions: Record<string, string>;
  definitions_sha256: string;
};

export type ProfileScope = {
  id: string;
  provider: "statsbomb" | "wyscout";
  competition: string;
  competition_key: string;
  season: string;
  gender: "male" | "female";
  matches: number;
  profiles: number;
  common_profiles: number;
  similarity_profiles: number;
  coverage: string;
  first_date: string;
  last_date: string;
};

export type StatsBombMetrics = {
  open_play_passes_per90: number | null;
  open_play_completion: number | null;
  crosses_per90: number | null;
  pressures_per90: number | null;
  carries_per90: number | null;
  dribbles_per90: number | null;
  tackles_per90: number | null;
  interceptions_per90: number | null;
  recoveries_per90: number | null;
  non_penalty_xg_per90: number | null;
};

export type WyscoutMetrics = {
  pass_events_per90: number | null;
  pass_event_completion: number | null;
  crosses_per90: number | null;
  key_passes_per90: number | null;
  duels_per90: number | null;
  attacking_duels_per90: number | null;
  sliding_tackles_per90: number | null;
  interceptions_per90: number | null;
  accelerations_per90: number | null;
  clearances_per90: number | null;
};
